name = "our-space-mailbox"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[kv_namespaces]]
binding = "MAILBOX"
id = "ad9ef91476734bf9bdf31fedb4deb496"

[vars]
ALLOWED_ORIGIN = "https://sameskytonight.vercel.app,http://localhost:5173"
